config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :sessions, only: [:new, :create, :destroy]

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get 'blood_selections/index'

  resources :patients, only: [:index] do
    resources :blood_selections, only: [:index]
  end

  resources :blood_bags, only: [:show] do
    resources :blood_bag_attributes, only: [:index] do
      collection do
        get :edit_all
        put :update_all
      end
    end
  end

  root to: "patients#index"
end

app/models/blood_bag_attribute.rb
class BloodBagAttribute
  include ActiveModel::AttributeMethods
  include ActiveModel::Serialization

  attr_accessor :id,
                :bbat_Id, :bbat_BloodBag,
                :bbat_BloodAttribute,
                :bbat_BloodAttributeMnemonic, :bbat_BloodAttributeName,
                :bbat_BloodAttrMinAfterStart, :bbat_BloodAttributeIsMandatory,
                :bbat_ExtraInfo,:bbat_Present

  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
    @id ||= object_id
  end

  # Define an +attributes+ method which returns a hash with each
  #   attribute name in your model as hash key and the attribute value as hash value.
  #   Hash keys must be strings
  # See also rails/activemodel/attribute_methods documentation
  def attributes
    {
        'id' => @id,
        'bbat_Id' => @bbat_Id, 'bbat_BloodBag' => @bbat_BloodBag, 'bbat_BloodAttribute' => @bbat_BloodAttribute,
        'bbat_BloodAttributeMnemonic' => @bbat_BloodAttributeMnemonic,
        'bbat_BloodAttributeName' => @bbat_BloodAttributeName,
        'bbat_BloodAttrMinAfterStart' => @bbat_BloodAttrMinAfterStart,
        'bbat_BloodAttributeIsMandatory' => @bbat_BloodAttributeIsMandatory,
        'bbat_ExtraInfo' => @bbat_ExtraInfo, 'bbat_Present' => @bbat_Present
    }
  end

  def to_json(options = nil)
    serializable_hash(options).to_json
  end

  def externalize
    bbat_BloodAttributeName ? bbat_BloodAttributeName : bbat_BloodAttributeMnemonic
  end

  def to_s
    "#{id}"
  end

  def update_attributes(attributes = {})
    attributes.each do |name, value|
      update_attribute(name, value)
    end
    if bbat_ExtraInfo
       @bbat_Present = true
    end
  end

  def update_attribute(name, value)
    name = name.to_s
    # verify_readonly_attribute(name)
    send("#{name}=", value)
  end

  def is_numeric?
    is_numeric = false
    if bbat_BloodAttributeMnemonic
      if (bbat_BloodAttributeMnemonic.start_with?('HBEAT') ||
          bbat_BloodAttributeMnemonic.start_with?('BLDPRESSURE') ||
          bbat_BloodAttributeMnemonic.match(/^P[0-9]+/) ||
          bbat_BloodAttributeMnemonic.match(/^R[0-9]+/))
        is_numeric = true
      end
    end
    is_numeric
  end

end

app/controllers/blood_bag_attribute_controller.rb
class BloodBagAttributeController < ApplicationController
  before_action :authenticate_user!, :basic_auth_credentials
  before_action :find_blood_bag

  def show
  end

  def index
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def find_blood_bag
    blood_bag_service = BloodBagService.new(session_login_user, session_password_user)
    response = blood_bag_service.find_by_id(params[:blood_bag_id])
    if response.code == 200
      @blood_bag = BloodBagDataSet.new(response).blood_bags.first
    end
  end
end

app/controllers/blood_bag_attributes_controller.rb
class BloodBagAttributesController < ApplicationController
  before_action :authenticate_user!, :basic_auth_credentials
  before_action :find_blood_bag, :setup_blood_bag_attribute_service

  def index
    @patient_id = params['patient_id']
    response = @blood_bag_attribute_service.blood_bag_attributes(@blood_bag.bbag_Id)
    if response.code == 200
      @blood_bag_attributes = BloodBagAttributeDataSet.parse(response).blood_bag_attributes
    else
      Rails.logger.error "HTTP response code = #{response.code}"
    end
  end

  def edit_all
    response = @blood_bag_attribute_service.blood_bag_attributes(@blood_bag.bbag_Id)
    if response.code == 200
      @blood_bag_attributes = BloodBagAttributeDataSet.parse(response).blood_bag_attributes
    end
  end

  def update_all
    before_blood_bag_attributes = parse_blood_bag_attributes_params(params['before_blood_bag_attributes'])
    params['blood_bag_attribute'].keys.each do |id|
      Rails.logger.info "id = #{id} params = #{params['blood_bag_attribute'][id]}"
      blood_bag_attribute = before_blood_bag_attributes.select {
          |blood_bag_attribute| blood_bag_attribute.id == id.to_i
      }.first
      blood_bag_attribute.update_attributes(params['blood_bag_attribute'][id])
    end
    response = @blood_bag_attribute_service.put_blood_bag_attribute_data_set(@blood_bag.bbag_Id,
      BloodBagAttributeDataSet.new(before_blood_bag_attributes))
    redirect_to blood_bag_blood_bag_attributes_url
  end

  private

  def find_blood_bag
    blood_bag_service = BloodBagService.new(session_login_user, session_password_user)
    response = blood_bag_service.find_by_id(params[:blood_bag_id])
    if response.code == 200
      @blood_bag = BloodBagDataSet.parse(response).blood_bags.first
    end
  end

  def setup_blood_bag_attribute_service
    @blood_bag_attribute_service = BloodBagAttributeService.new(session_login_user, session_password_user)
  end

  def parse_blood_bag_attributes_params(blood_bag_attributes_params)
    blood_bag_attributes = []
    if blood_bag_attributes_params
      blood_bag_attributes_hash = JSON.parse(blood_bag_attributes_params)
      blood_bag_attributes_hash.each do |blood_bag_attribute_hash|
        blood_bag_attributes << BloodBagAttribute.new(blood_bag_attribute_hash)
      end
    end
    blood_bag_attributes
  end
end

app/helpers/blood_bag_attributes_helper.rb
require 'plot'

module BloodBagAttributesHelper
  def jsonify(blood_bag_attributes)
    blood_bag_attributes.map(&:serializable_hash).to_json
  end

  def parameters_label(label)
    "#{label}"
  end

  def anchor_href(label)
    "\##{label}"
  end

  def graph_plots(blood_bag_attributes)
    plots = []
    grouper = BloodBagAttributesGrouper.new(blood_bag_attributes)
    grouper.attributes.each do |attribute|
        if attribute.coordinates?
          plot = Graph::Plot.new(attribute.key, attribute.coordinates)
          plots << plot
        end
    end
    plots
  end

  def graph_plots?(blood_bag_attributes)
    graph_plots(blood_bag_attributes).length > 0
  end

end

app/views/blood_bag_attributes/tabs_navbar/_blood_bag_attribute_group.mobile.erb
<div id="<%= group.label %>">
  <h2><%= parameters_label(group.label) %></h2>
  <ul data-role="listview" data-inset="true">
    <% group.attributes.each do |blood_bag_attribute| %>
      <li>
        <%= label_tag :externalize, blood_bag_attribute.externalize %>
        <%= blood_bag_attribute.bbat_ExtraInfo %>
      </li>
    <% end %>
  </ul>
</div>

app/views/blood_bag_attributes/tabs_navbar/_edit_all.mobile.erb
<div data-role="header">
  <h2><%= t('blood_bag_attributes.helpers.label.listing') %></h2>
</div>
<div data-role="content">
  <div class="ui-body ui-body-a">
    <%= render partial: 'blood_bag', locals: { blood_bag: @blood_bag } %>
  </div>
  <div id="blood_bag_attributes_container">
    <h2>Parameters</h2>
    <%= form_for :blood_bag_attributes, :url => update_all_blood_bag_blood_bag_attributes_path, :html => { :method => :put, :multipart => true } do %>
        <%= hidden_field_tag :before_blood_bag_attributes, jsonify(@blood_bag_attributes) %>
        <% grouper = BloodBagAttributesGrouper.new(@blood_bag_attributes) %>
        <div data-role="tabs">
          <%= render partial: 'blood_bag_attributes/tabs_navbar/group_navbar', locals: { grouper: grouper} %>
          <% grouper.groups.each do |group| %>
              <%= render :partial => 'blood_bag_attributes/tabs_navbar/edit_blood_bag_attribute_group', locals: { group: group } %>
          <% end %>
        </div>
        <div class="actions">
          <%= submit_tag 'Update parameters' %>
        </div>
    <% end %>
  </div>
  <div data-role="navbar">
    <ul>
      <li>
        <%= link_to blood_bag_blood_bag_attributes_path do %>
            <%= image_tag('black/back.png', class: 'button_image_text') %>
            <%= t('application.helpers.label.back') %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/blood_bag_attributes/tabs_navbar/_edit_blood_bag_attribute_group.mobile.erb
<div id="<%= group.label %>">
  <h2><%= parameters_label(group.label) %></h2>
  <ul data-role="listview" data-inset="true">
    <% group.attributes.each do |blood_bag_attribute| %>
      <%= fields_for "blood_bag_attribute[]", blood_bag_attribute do |blood_bag_attribute_fields| %>
        <div>
          <%= label_tag :externalize, blood_bag_attribute.externalize %>
          <% if blood_bag_attribute.is_numeric? %>
              <%= blood_bag_attribute_fields.range_field :bbat_ExtraInfo, { data: { highlight: true}, min: '40', max: '250' } %>
          <% else %>
            <%= blood_bag_attribute_fields.text_field :bbat_ExtraInfo %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/blood_bag_attributes/tabs_navbar/_group_navbar.mobile.erb
<div data-role="navbar">
  <ul>
    <% grouper.groups.each_with_index do |group, index| %>
        <% if index == 0 %>
            <li><%= link_to group.label, anchor_href(group.label), { data: { theme: 'c', ajax: false }, class: 'ui-btn-active'} %></li>
        <% else %>
            <li><%= link_to group.label, anchor_href(group.label), { data: { theme: 'c', ajax: false } } %></li>
        <% end %>
    <% end %>
  </ul>
</div>

app/views/blood_bag_attributes/tabs_navbar/_index.mobile.erb
<div data-role="header">
  <h2><%= t('blood_bag_attributes.helpers.label.listing') %></h2>
</div>
<div data-role="content">
  <div class="ui-body ui-body-a">
    <%= render :partial => 'blood_bag', locals: { blood_bag: blood_bag } %>
  </div>
  <div id="blood_bag_attributes_container">
    <h2>Parameters</h2>
    <% grouper = BloodBagAttributesGrouper.new(blood_bag_attributes) %>
    <div data-role="tabs">
      <%= render partial: 'blood_bag_attributes/tabs_navbar/group_navbar', locals: { grouper: grouper} %>
      <% grouper.groups.each do |group| %>
        <%= render partial: 'blood_bag_attributes/tabs_navbar/blood_bag_attribute_group', locals: { group: group} %>
      <% end %>
    </div>
  </div>
  <div data-role="navbar">
    <ul>
      <li>
        <%= link_to patient_id ? patient_blood_selections_path(patient_id) : patients_path, class: :anchorButton do %>
            <%= image_tag('black/back.png', class: 'button_image_text') %>
            <%= t('application.helpers.label.back') %>
        <% end %>
      </li>
      <li>
        <%= link_to edit_all_blood_bag_blood_bag_attributes_path blood_bag.bbag_Id do %>
            <%= image_tag('black/edit.png', class: 'button_image_text') %>
            <%= t('application.helpers.label.edit') %>
        <% end %>
      </li>
    </ul>
  </div>
</div>