config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)

  resources :sessions, only: [:new, :create, :destroy]

  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"

  get 'blood_selections/index'

  resources :patients, only: [:index] do
    resources :blood_selections, only: [:index]
  end

  resources :blood_bags, only: [:show] do
    resources :blood_bag_attributes, only: [:index] do
      collection do
        get :edit_all
        put :update_all
      end
    end
  end

  root to: "patients#index"
end

app/views/shared/_header.mobile.erb
<div data-role="header" data-theme="a" class="mobile_header">
  <h1>CyberTrack</h1>
  <% if current_user? %>
    <a href="#nav-panel" data-icon="bars" data-iconpos="notext">Menu</a>
  <% end %>
  <%= image_tag('branding/32x32/blood_transfusion.png', alt: 'logo app', border: '1', class: "ui-btn-right", id: 'logo_image') %>
</div><!-- /header -->

<div data-role="panel" data-position="left" data-position-fixed="false" data-display="reveal" id="nav-panel" data-theme="a">

  <ul data-role="listview" data-theme="a" data-divider-theme="a" style="margin-top:-16px;" class="nav-search">
    <li data-icon="delete" style="background-color:#111;">
      <a href="#" data-rel="close"><%= t('application.helpers.menu.close') %></a>
    </li>
    <!--An example form jquery mobile slide menu vertical-->
    <!--<li data-filtertext="button icon">-->
    <!--<a href="buttons/buttons-icons.html">Button icons</a>-->
    <!--</li>-->
    <li>
      <%= link_to t('application.helpers.menu.patients'), patients_url, data: { ajax: false } %>
    </li>
    <li>
      <%= link_to t('application.helpers.menu.sign_out'), logout_path, data: { ajax: false } %>
    </li>
  </ul>

  <!-- panel content goes here -->
</div><!-- /panel -->

<div class="flash">
  <% flash.each do |key, msg| %>
      <%= content_tag :div, msg, :class => [key, " message"], :id => "notice_ #{key}" %>
  <% end %>
</div>

app/views/shared/_record_field.mobile.erb
<% unless field.blank? %>
    <p>
      <%= label_tag tag, label %>
      <% if class_attribute %>
          <%= content_tag 'div', class: class_attribute do %>
              <%= data_type == :date_time ? l(json_to_datetime(field)) : field %>
          <% end %>
      <% else %>
          <%= content_tag 'div' do %>
              <%= data_type == :date_time ? l(json_to_datetime(field)) : field %>
          <% end %>
      <% end %>
    </p>
<% end %>